cleanup commands/scripts

diff --git a/templates/ra_guac_autoscale_public_alb.template.cfn.yaml b/templates/ra_guac_autoscale_public_alb.template.cfn.yaml
--- a/templates/ra_guac_autoscale_public_alb.template.cfn.yaml
+++ b/templates/ra_guac_autoscale_public_alb.template.cfn.yaml
@@ -46,8 +46,8 @@ Conditions:
     - !Equals
       - !Ref URLText2
       - ''
-Description: This templates deploys Guacamole (Guac) instances in an AutoScale Group behindan ALB
-Mappi ngs:
+Description: This templates deploys Guacamole (Guac) instances in an AutoScale Group behind an ALB
+Mappings:
   InstanceTypeMap:
     'Fn::Transform':
       Name: 'AWS::Include'
@@ -69,7 +69,7 @@ Outputs:
     Value: !Ref Ec2SecurityGroup
   LoadBalancerDns:
     Description: DNS name for the ALB
-    Value: !GetAtt ALB.DNSName
+    Value: !Sub ${ALB.DNSName}
   LoadBalancerName:
     Description: Name of the ALB
     Value: !Ref ALB
@@ -99,9 +99,7 @@ Parameters:
       - A
       - B
     Default: A
-    Description: >-
-      A/B toggle that forces a change to a LaunchConfig property, triggering the
-      AutoScale Update Policy
+    Description: A/B toggle that forces a change to a LaunchConfig property, triggering the AutoScale Update Policy
     Type: String
   GuacBaseDN:
     Default: CN=GuacConfigGroups
@@ -314,9 +312,7 @@ Resources:
     Properties:
       AlarmActions:
         - !Ref ScaleUpPolicy
-      AlarmDescription: >-
-        Scale-up if CPU > 30% for 5 minutes or metric disappears indicating
-        instance is down
+      AlarmDescription: Scale-up if CPU > 30% for 5 minutes or metric disappears indicating instance is down
       ComparisonOperator: GreaterThanThreshold
       Dimensions:
         - Name: AutoScalingGroupName
@@ -446,8 +442,7 @@ Resources:
         finalize:
           commands:
             10-signal-success:
-              command: !Sub >-
-                /opt/aws/bin/cfn-signal -e 0 --stack ${AWS::StackName} --resource AutoScalingGroup --region ${AWS::Region}
+              command: !Sub /opt/aws/bin/cfn-signal -e 0 --stack ${AWS::StackName} --resource AutoScalingGroup --region ${AWS::Region}
               ignoreErrors: 'true'
         make-guac:
           commands:
@@ -529,61 +524,57 @@ Resources:
             VolumeType: gp2
       EbsOptimized: !FindInMap [InstanceTypeMap, !Ref InstanceType, SupportsEbsOptimized]
       IamInstanceProfile: !Ref Ec2IamInstanceProfile
-      ImageId: !If [UseAmiLookup, !Sub '${AmiId}', '']
+      ImageId: !If [UseAmiLookup, !Sub '${AmiIdLookup.Id}',!Ref AmiId]
       InstanceType: !Ref InstanceType
       KeyName: !Ref KeyPairName
       SecurityGroups:
         - !Ref Ec2SecurityGroup
       UserData:
-        Fn::Base64: !Sub
-          - |
-            #!/bin/bash -xe
+        Fn::Base64: !Sub |
+          #!/bin/bash -xe
+          # CFN LaunchConfig Update Toggle: ${ForceUpdateToggle}
 
-            # CFN LaunchConfig Update Toggle:
-            ${ForceUpdateToggle}
+          # Get pip
+          curl --silent --show-error --retry 5 -L https://bootstrap.pypa.io/get-pip.py | python
 
-            # Get pip
-            curl --silent --show-error --retry 5 -L https://bootstrap.pypa.io/get-pip.py | python
+          # Add pip to path
+          hash pip 2> /dev/null || PATH="${!PATH}:/usr/local/bin"
 
-            # Add pip to path
-            hash pip 2> /dev/null || PATH="${!PATH}:/usr/local/bin"
+          # Upgrade setuptools
+          pip install --upgrade setuptools
 
-            # Upgrade setuptools
-            pip install --upgrade setuptools
+          # Fix python urllib3 warnings
+          yum -y install gcc python-devel libffi-devel openssl-devel
+          pip install pyopenssl ndg-httpsclient pyasn1
 
-            # Fix python urllib3 warnings
-            yum -y install gcc python-devel libffi-devel openssl-devel
-            pip install pyopenssl ndg-httpsclient pyasn1
+          # Get cfn utils
+          pip install https://s3.amazonaws.com/cloudformation-examples/aws-cfn-bootstrap-latest.tar.gz
 
-            # Get cfn utils
-            pip install https://s3.amazonaws.com/cloudformation-examples/aws-cfn-bootstrap-latest.tar.gz
+          # Remove gcc now that it is no longer needed
+          yum -y remove gcc --setopt=clean_requirements_on_remove=1
 
-            # Remove gcc now that it is no longer needed
-            yum -y remove gcc --setopt=clean_requirements_on_remove=1
+          # Fixup cfn utils
+          INITDIR=$(find -L /opt/aws/apitools/cfn-init/init -name redhat 2> /dev/null || echo /usr/init/redhat)
+          chmod 775 ${!INITDIR}/cfn-hup
+          ln -f -s ${!INITDIR}/cfn-hup /etc/rc.d/init.d/cfn-hup
+          chkconfig --add cfn-hup
+          chkconfig cfn-hup on
+          mkdir -p /opt/aws/bin
+          BINDIR=$(find -L /opt/aws/apitools/cfn-init -name bin 2> /dev/null || echo /usr/bin)
+          for SCRIPT in cfn-elect-cmd-leader cfn-get-metadata cfn-hup cfn-init cfn-send-cmd-event cfn-send-cmd-result cfn-signal
+          do
+            ln -s ${!BINDIR}/${!SCRIPT} /opt/aws/bin/${!SCRIPT} 2> /dev/null || echo Skipped symbolic link, /opt/aws/bin/${!SCRIPT} already exists
+          done
 
-            # Fixup cfn utils
-            INITDIR=$(find -L /opt/aws/apitools/cfn-init/init -name redhat 2> /dev/null || echo /usr/init/redhat)
-            chmod 775 ${INITDIR}/cfn-hup
-            ln -f -s ${INITDIR}/cfn-hup /etc/rc.d/init.d/cfn-hup
-            chkconfig --add cfn-hup
-            chkconfig cfn-hup on
-            mkdir -p /opt/aws/bin
-            BINDIR=$(find -L /opt/aws/apitools/cfn-init -name bin 2> /dev/null || echo /usr/bin)
-            for SCRIPT in cfn-elect-cmd-leader cfn-get-metadata cfn-hup cfn-init cfn-send-cmd-event cfn-send-cmd-result cfn-signal
-            do
-              ln -s ${BINDIR}/${SCRIPT} /opt/aws/bin/${SCRIPT} 2> /dev/null || echo Skipped symbolic link, /opt/aws/bin/${SCRIPT} already exists
-            done
+          # Add cfn utils to path
+          hash cfn-signal 2> /dev/null || PATH="${!PATH}:/usr/local/bin:/opt/aws/bin"
 
-            # Add cfn utils to path
-            hash cfn-signal 2> /dev/null || PATH="${!PATH}:/usr/local/bin:/opt/aws/bin"
+          # Install ssm agent
+          yum -y install https://s3.amazonaws.com/ec2-downloads-windows/SSMAgent/latest/linux_amd64/amazon-ssm-agent.rpm || true
 
-            # Install ssm agent
-            yum -y install https://s3.amazonaws.com/ec2-downloads-windows/SSMAgent/latest/linux_amd64/amazon-ssm-agent.rpm || true
+          # Execute cfn-init
+          /opt/aws/bin/cfn-init -v -c config --stack ${AWS::StackName} --resource LaunchConfig --region ${AWS::Region} || (echo 'ERROR: cfn-init failed! Aborting!'; /opt/aws/bin/cfn-signal -e 1 --stack ${AWS::StackName} --resource AutoScalingGroup --region ${AWS::Region}; exit 1)
 
-            # Execute cfn-init
-            /opt/aws/bin/cfn-init -v -c config --stack ${AWS::StackName} --resource LaunchConfig --region ${AWS::Region} || \
-            (echo 'ERROR: cfn-init failed! Aborting!'; /opt/aws/bin/cfn-signal -e 1 --stack ${AWS::StackName} \
-            --resource AutoScalingGroup --region ${AWS::Region}'; exit 1)
     Type: 'AWS::AutoScaling::LaunchConfiguration'
   Listener:
     Properties:
@@ -591,8 +582,8 @@ Resources:
         - CertificateArn:
             !If
               - UseACM
-              - !Sub 'arn:aws:acm:${AWS::Region}:${AWS:AccountId}:certificate/${SslCertificateName}'
-              - !Sub 'arn:aws:acm:${AWS::Region}:${AWS:AccountId}:server-certificate/${SslCertificateName}'
+              - !Sub 'arn:aws:acm:${AWS::Region}:${AWS::AccountId}:certificate/${SslCertificateName}'
+              - !Sub 'arn:aws:acm:${AWS::Region}:${AWS::AccountId}:server-certificate/${SslCertificateName}'
       DefaultActions:
         - TargetGroupArn: !Ref ALBTargetGroup
           Type: forward
